#include "MainWindow.h"
#include "Viewport3D.h"
#include "cnc/ProgramLoader.h"
#include "cnc/Verify.h"
#include <fstream>
#include <QPlainTextEdit>
#include <QLabel>
#include <QPushButton>
#include <QListWidget>
#include <QTreeWidget>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QGridLayout>
#include <QFileDialog>
#include <QFileInfo>
#include <QMessageBox>
#include <QTimer>
#include <QLineEdit>
#include <QDoubleSpinBox>
#include <QCheckBox>
#include <QComboBox>
#include <QFormLayout>
#include <QHash>
MainWindow::MainWindow(QWidget* p):QMainWindow(p),operator_(runtime_){
 setWindowTitle("CNC5AxisSim - Siemens 840D / 5-Axis");
 resize(1200,760);
 auto* root=new QWidget(this);auto* main=new QHBoxLayout(root);
 program_=new QPlainTextEdit; program_->setPlaceholderText("Paste Siemens 840D MPF program here...");
 auto* center=new QVBoxLayout; viewport_=new Viewport3D(&runtime_); center->addWidget(viewport_,2); center->addWidget(program_,1); main->addLayout(center,3);
 auto* timer=new QTimer(this); timer->setInterval(50); connect(timer,&QTimer::timeout,this,[this,timer]{ if(operator_.executor().state()==cnc::ExecutionState::Running){ if(!operator_.step()){timer->stop();} refresh(); } else timer->stop(); });
 auto* right=new QVBoxLayout; auto* machineBox=new QVBoxLayout; auto* machineLabel=new QLabel("MACHINE KINEMATIC TREE"); machine_tree_=new QTreeWidget; machine_tree_->setHeaderLabels({"Node","Type","Parent","Limit","Mesh"}); machine_tree_->setRootIsDecorated(true); machineBox->addWidget(machineLabel); machineBox->addWidget(machine_tree_,1); auto* loadMachine=new QPushButton("LOAD MACHINE JSON"); connect(loadMachine,&QPushButton::clicked,this,[this]{QString fn=QFileDialog::getOpenFileName(this,"Open Machine JSON",{}, "JSON (*.json);;All Files (*)");if(fn.isEmpty())return;std::string e;if(!runtime_.load_machine_config(fn.toStdString(),e)){QMessageBox::critical(this,"MACHINE",QString::fromStdString(e));return;} machine_tree_->clear(); const auto& nodes=runtime_.machine_nodes(); (void)nodes; refresh(); if(viewport_)viewport_->update(); }); machineBox->addWidget(loadMachine);
 auto* editBox=new QFormLayout; auto* machineNameEdit=new QLineEdit(QString::fromStdString(runtime_.machine_name())); auto* nameEdit=new QLineEdit; auto* parentEdit=new QLineEdit; auto* ax=new QDoubleSpinBox;auto* ay=new QDoubleSpinBox;auto* az=new QDoubleSpinBox;auto* px=new QDoubleSpinBox;auto* py=new QDoubleSpinBox;auto* pz=new QDoubleSpinBox;auto* minEdit=new QDoubleSpinBox;auto* maxEdit=new QDoubleSpinBox;auto* wrapEdit=new QCheckBox("Wrap");auto* typeEdit=new QComboBox;typeEdit->addItems({"Linear","Rotary","Tool","Holder","Fixture"});auto* collisionEdit=new QCheckBox("Collision");for(auto*w:{ax,ay,az,px,py,pz,minEdit,maxEdit}){w->setRange(-100000,100000);w->setDecimals(4);}editBox->addRow("Machine",machineNameEdit);editBox->addRow("Name",nameEdit);editBox->addRow("Parent",parentEdit);editBox->addRow("Axis X",ax);editBox->addRow("Axis Y",ay);editBox->addRow("Axis Z",az);editBox->addRow("Pivot X",px);editBox->addRow("Pivot Y",py);editBox->addRow("Pivot Z",pz);editBox->addRow("Min",minEdit);editBox->addRow("Max",maxEdit);editBox->addRow(wrapEdit);editBox->addRow(collisionEdit);
 auto* applyNode=new QPushButton("APPLY NODE");auto* addNode=new QPushButton("ADD NODE");auto* deleteNode=new QPushButton("DELETE NODE");auto* meshBrowse=new QPushButton("MESH...");auto* saveMachine=new QPushButton("SAVE MACHINE JSON");machineBox->addLayout(editBox);machineBox->addWidget(meshBrowse);machineBox->addWidget(applyNode);machineBox->addWidget(addNode);machineBox->addWidget(deleteNode);machineBox->addWidget(saveMachine);
 connect(machine_tree_,&QTreeWidget::itemClicked,this,[=](QTreeWidgetItem*i,int){if(!i)return;nameEdit->setText(i->text(0));parentEdit->setText(i->text(2));for(const auto&n:runtime_.machine_nodes())if(QString::fromStdString(n.name)==i->text(0)){typeEdit->setCurrentIndex(n.type==cnc::MachineNodeType::LinearAxis?0:n.type==cnc::MachineNodeType::RotaryAxis?1:n.type==cnc::MachineNodeType::Tool?2:n.type==cnc::MachineNodeType::Holder?3:4);collisionEdit->setChecked(n.collision_enabled);ax->setValue(n.axis.x);ay->setValue(n.axis.y);az->setValue(n.axis.z);px->setValue(n.pivot.x);py->setValue(n.pivot.y);pz->setValue(n.pivot.z);minEdit->setValue(n.min);maxEdit->setValue(n.max);wrapEdit->setChecked(n.wrap);}});
 connect(meshBrowse,&QPushButton::clicked,this,[=]{QString fn=QFileDialog::getOpenFileName(this,"Select Machine Mesh",{}, "Mesh (*.stl *.STL);;All Files (*)");if(!fn.isEmpty())nameEdit->setProperty("meshPath",fn);});
 connect(addNode,&QPushButton::clicked,this,[=]{cnc::MachineNode n;n.name=nameEdit->text().toStdString();n.parent=parentEdit->text().toStdString();n.axis={ax->value(),ay->value(),az->value()};n.pivot={px->value(),py->value(),pz->value()};n.min=minEdit->value();n.max=maxEdit->value();n.wrap=wrapEdit->isChecked();n.collision_enabled=collisionEdit->isChecked();n.type=typeEdit->currentIndex()==0?cnc::MachineNodeType::LinearAxis:typeEdit->currentIndex()==1?cnc::MachineNodeType::RotaryAxis:typeEdit->currentIndex()==2?cnc::MachineNodeType::Tool:typeEdit->currentIndex()==3?cnc::MachineNodeType::Holder:cnc::MachineNodeType::Fixture;n.mesh=nameEdit->property("meshPath").toString().toStdString();std::string e;if(!runtime_.add_machine_node(n,e))QMessageBox::critical(this,"MACHINE",QString::fromStdString(e));else{machine_tree_->clear();refresh();viewport_->update();}});
 connect(deleteNode,&QPushButton::clicked,this,[=]{auto*i=machine_tree_->currentItem();if(!i)return;std::string e;if(!runtime_.remove_machine_node(i->text(0).toStdString(),e))QMessageBox::critical(this,"MACHINE",QString::fromStdString(e));else{machine_tree_->clear();refresh();viewport_->update();}});
 connect(applyNode,&QPushButton::clicked,this,[=]{for(auto n:runtime_.machine_nodes())if(QString::fromStdString(n.name)==nameEdit->text()){n.parent=parentEdit->text().toStdString();n.axis={ax->value(),ay->value(),az->value()};n.pivot={px->value(),py->value(),pz->value()};n.min=minEdit->value();n.max=maxEdit->value();n.wrap=wrapEdit->isChecked();n.collision_enabled=collisionEdit->isChecked();n.type=typeEdit->currentIndex()==0?cnc::MachineNodeType::LinearAxis:typeEdit->currentIndex()==1?cnc::MachineNodeType::RotaryAxis:typeEdit->currentIndex()==2?cnc::MachineNodeType::Tool:typeEdit->currentIndex()==3?cnc::MachineNodeType::Holder:cnc::MachineNodeType::Fixture;std::string e;if(!runtime_.update_machine_node(n,e))QMessageBox::critical(this,"MACHINE",QString::fromStdString(e));else{machine_tree_->clear();refresh();if(viewport_)viewport_->update();}break;}});
 connect(saveMachine,&QPushButton::clicked,this,[this]{QString fn=QFileDialog::getSaveFileName(this,"Save Machine JSON",{}, "JSON (*.json)");if(fn.isEmpty())return;std::string e;if(!runtime_.save_machine_config(fn.toStdString(),e))QMessageBox::critical(this,"MACHINE",QString::fromStdString(e));});
 right->addLayout(machineBox,2); auto* pos=new QGridLayout;
 x_=new QLabel;y_=new QLabel;z_=new QLabel;a_=new QLabel;c_=new QLabel;feed_=new QLabel;rpm_=new QLabel;status_=new QLabel;
 const char* names[]={"X","Y","Z","A","C","F","S"}; QLabel* vals[]={x_,y_,z_,a_,c_,feed_,rpm_};
 for(int i=0;i<7;++i){pos->addWidget(new QLabel(names[i]),i,0);pos->addWidget(vals[i],i,1);}
 right->addLayout(pos); right->addWidget(status_);
 auto add=[&](const char* t,auto fn){auto* b=new QPushButton(t);connect(b,&QPushButton::clicked,this,fn);right->addWidget(b);};
 add("START",[this,timer]{ if(operator_.start()) { timer->start(); } refresh(); });
 add("STEP",[this]{operator_.step();refresh();centralWidget()->update();});
 add("HOLD",[this]{operator_.hold();refresh();});
 add("RESUME",[this]{operator_.resume();refresh();});
 add("STOP",[this,timer]{timer->stop();operator_.stop();refresh();});
 add("RESET",[this,timer]{timer->stop();operator_.reset();refresh();});
 add("VERIFY",[this]{cnc::ProgramLoader l;std::string e;if(!l.load_text(program_->toPlainText().toStdString(),e)){QMessageBox::critical(this,"VERIFY",QString::fromStdString(e));return;} auto r=cnc::VerifyEngine::run(l.blocks(),catalog_.subprograms()); QString msg=QString("VERIFY %1 | blocks %2/%3 | errors %4 | collisions %5").arg(r.passed?"PASS":"FAIL").arg((qulonglong)r.executed).arg((qulonglong)l.blocks().size()).arg((qulonglong)r.errors).arg((qulonglong)r.collisions); status_->setText(msg); if(!r.passed) QMessageBox::warning(this,"VERIFY",msg+"\n"+QString::fromStdString(r.first_error)); else QMessageBox::information(this,"VERIFY",msg); std::string re; cnc::VerifyEngine::save_json(r,"verify.json",re); if(!re.empty()) alarms_->addItem(QString::fromStdString(re));});
 auto* load=new QPushButton("LOAD MPF");connect(load,&QPushButton::clicked,this,[this]{QString fn=QFileDialog::getOpenFileName(this,"Open MPF",{}, "MPF (*.MPF *.mpf);;All Files (*)");if(fn.isEmpty())return;cnc::ProgramLoader l;std::string e;if(!l.load_file(fn.toStdString(),e)){QMessageBox::critical(this,"MPF",QString::fromStdString(e));return;}operator_.load(l.blocks()); catalog_.load_directory(QFileInfo(fn).absolutePath().toStdString(),e); for(const auto& [n,b]:catalog_.subprograms()) operator_.add_subprogram(n,b); std::ifstream in(fn.toStdString(),std::ios::binary);std::string text((std::istreambuf_iterator<char>(in)),std::istreambuf_iterator<char>());program_->setPlainText(QString::fromStdString(text)); refresh();});right->addWidget(load);
 alarms_=new QListWidget;right->addWidget(alarms_,1);main->addLayout(right,1);setCentralWidget(root);loadDemo();
}
void MainWindow::loadDemo(){program_->setPlainText("N10 G90 G54 G0 X0 Y0 Z100\nN20 T1 D1 S8000 M3\nN30 G1 X100 Y50 Z20 A30 C45 F1000\nN40 G91 X5 C20\nN50 G90 G55 G0 X0 Y0 Z100\nN60 M5");cnc::ProgramLoader l;std::string e;l.load_text(program_->toPlainText().toStdString(),e);operator_.load(l.blocks());refresh();}
void MainWindow::refresh(){auto s=runtime_.state();x_->setText(QString::number(s.X,'f',3));y_->setText(QString::number(s.Y,'f',3));z_->setText(QString::number(s.Z,'f',3));a_->setText(QString::number(s.A,'f',3));c_->setText(QString::number(s.C,'f',3));feed_->setText(QString::number(runtime_.feed(),'f',1));rpm_->setText(QString::number(runtime_.rpm(),'f',0));status_->setText(QString::fromStdString(runtime_.alarm().empty()?"READY":runtime_.alarm())); if(operator_.executor().state()==cnc::ExecutionState::Running) status_->setText(QString("RUN N%1 | P%2").arg((qulonglong)operator_.executor().current_block()).arg(operator_.executor().current_program()));if(machine_tree_ && machine_tree_->topLevelItemCount()==0 && !runtime_.machine_nodes().empty()){const auto& rn=runtime_.machine_nodes();QHash<QString,QTreeWidgetItem*> map;for(const auto& n:rn){QTreeWidgetItem* item=n.parent.empty()?new QTreeWidgetItem(machine_tree_):new QTreeWidgetItem;item->setText(0,QString::fromStdString(n.name));item->setText(1,n.type==cnc::MachineNodeType::LinearAxis?"Linear":n.type==cnc::MachineNodeType::RotaryAxis?"Rotary":n.type==cnc::MachineNodeType::Tool?"Tool":n.type==cnc::MachineNodeType::Holder?"Holder":"Fixture");item->setText(2,QString::fromStdString(n.parent));item->setText(3,QString("[%1 .. %2]%3").arg(n.min).arg(n.max).arg(n.wrap?" wrap":""));item->setText(4,QString::fromStdString(n.mesh));map.insert(QString::fromStdString(n.name),item);}for(const auto& n:rn)if(!n.parent.empty()&&map.contains(QString::fromStdString(n.parent)))map[QString::fromStdString(n.parent)]->addChild(map[QString::fromStdString(n.name)]); } if(alarms_){alarms_->clear();for(auto&e:runtime_.collisions().events())alarms_->addItem(QString("N%1  %2").arg(e.block_number).arg(QString::fromStdString(e.message)));}}
