#include "MachineJson.h"
#include <cctype>
#include <cmath>
#include <cstring>
#include <iomanip>
#include <sstream>
namespace cnc {
class JParser{const std::string&s;size_t p=0;std::string&e;void ws(){while(p<s.size()&&std::isspace((unsigned char)s[p]))++p;}bool lit(const char*x){size_t n=std::strlen(x);if(s.compare(p,n,x))return false;p+=n;return true;}bool str(std::string&o){if(p>=s.size()||s[p++]!='"')return false;while(p<s.size()){char c=s[p++];if(c=='"')return true;if(c=='\\'){if(p>=s.size())return false;char q=s[p++];const char*esc="\"\\/bfnrt";const char*at=std::strchr(esc,q);if(!at)return false;o+= q=='n'?'\n':q=='r'?'\r':q=='t'?'\t':q=='b'?'\b':q=='f'?'\f':q;}else o+=c;}return false;}bool val(JsonValue&o){ws();if(p>=s.size())return false;if(s[p]=='{'){++p;JsonValue::Object m;ws();if(p<s.size()&&s[p]=='}'){++p;o=JsonValue(m);return true;}for(;;){ws();std::string k;if(!str(k))return false;ws();if(p>=s.size()||s[p++]!=':')return false;JsonValue v;if(!val(v))return false;m.emplace(std::move(k),std::move(v));ws();if(p<s.size()&&s[p]=='}'){++p;break;}if(p>=s.size()||s[p++]!=',')return false;}o=JsonValue(std::move(m));return true;}if(s[p]=='['){++p;JsonValue::Array a;ws();if(p<s.size()&&s[p]==']'){++p;o=JsonValue(a);return true;}for(;;){JsonValue v;if(!val(v))return false;a.push_back(std::move(v));ws();if(p<s.size()&&s[p]==']'){++p;break;}if(p>=s.size()||s[p++]!=',')return false;}o=JsonValue(std::move(a));return true;}if(s[p]=='"'){std::string x;if(!str(x))return false;o=JsonValue(x);return true;}if(s.compare(p,4,"true")==0){p+=4;o=JsonValue(true);return true;}if(s.compare(p,5,"false")==0){p+=5;o=JsonValue(false);return true;}if(s.compare(p,4,"null")==0){p+=4;o=JsonValue();return true;}char*end=nullptr;double n=std::strtod(s.c_str()+p,&end);if(end==s.c_str()+p||!std::isfinite(n))return false;p=(size_t)(end-s.c_str());o=JsonValue(n);return true;}public:JParser(const std::string&x,std::string&er):s(x),e(er){}bool run(JsonValue&o){if(!val(o)){e="invalid JSON";return false;}ws();if(p!=s.size()){e="trailing JSON data";return false;}return true;}};
bool parse_json(const std::string&t,JsonValue&o,std::string&e){return JParser(t,e).run(o);}
std::string json_escape(const std::string&s){std::string o;for(char c:s){if(c=='"'||c=='\\'){o+='\\';o+=c;}else if(c=='\n')o+="\\n";else if(c=='\r')o+="\\r";else if(c=='\t')o+="\\t";else o+=c;}return o;}
